import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Next 15",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex min-h-screen flex-col">
          <nav className="flex items-center space-x-6 border-b px-8 py-5">
            <Link href="/" className="text-sm font-medium hover:opacity-75">
              Home
            </Link>
            <Link href="/form-demo" className="text-sm font-medium hover:opacity-75">
              Form Demo
            </Link>
            <Link href="/async-api" className="text-sm font-medium hover:opacity-75">
              Async API
            </Link>
          </nav>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
